version: "3.8"

services:
  gateway:
    build: ./gateway
    image: gateway:dev
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - file-storing
      - file-analysis

  file-storing:
    build: ./file-storing
    image: file-storing:dev
    container_name: file-storing
    restart: unless-stopped
    ports:
      - "8001:8001"

  file-analysis:
    build: ./file-analysis
    image: file-analysis:dev
    container_name: file-analysis
    restart: unless-stopped
    ports:
      - "8002:8002"
    depends_on:
      - file-storing
