version: "3.8"

services:
  gateway:
    build: ./gateway
    image: gateway:dev
    container_name: gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      FILE_STORING_URL: "http://file-storing:8001"
      FILE_ANALYSIS_URL: "http://file-analysis:8002"
    depends_on:
      - file-storing
      - file-analysis

  file-storing:
    build: ./file-storing
    image: file-storing:dev
    container_name: file-storing
    restart: unless-stopped
    ports:
      - "8001:8001"
    volumes:
      - ./file-storing/storage:/app/storage

  file-analysis:
    build: ./file-analysis
    image: file-analysis:dev
    container_name: file-analysis
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      FILE_STORING_URL: "http://file-storing:8001"
    volumes:
      - ./file-analysis/results:/app/results
    depends_on:
      - file-storing
